default: &default
  adapter: postgresql
  encoding: unicode
  database: birdy
  user: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: birdy_test

staging:
  <<: *default
  database: <%= ENV["PG_DB_BIRDY"] %>

production:
  <<: *default
  database: <%= ENV["PG_DB_BIRDY"] %>
