:dynamic: true
:schedule:
  recalculate_videos_rank_job:
    every: 60m
    class: RecalculateVideosRankJob
  recalculate_tags_rank_job:
    every: 30m
    class: RecalculateTagsRankJob
  recalculate_top_contributors_job:
    every: 2m
    class: RecalculateTopContributorsJob
  update_untagged_video_job:
    every: 30m
    class: UpdateUntaggedVideoJob
  wasp_post_job:
    every: 60m
    class: WaspPostJob
  weekly_mailing_job:
    cron: '0 9 * * 1'
    class: WeeklyMailingJob

:queues:
  - rank_calculation
  - video_tag_expiration
  - wasp_outreach
  - wasp_post
  - twitter_posting
  - default
  - mailers
