:schedule:
  recalculate_videos_rank_job:
    every: 1m
    class: RecalculateVideosRankJob
  recalculate_tags_rank_job:
    every: 1m
    class: RecalculateTagsRankJob
  update_untagged_video_job:
    every: 1m
    class: UpdateUntaggedVideoJob
:queues:
  - default
  - mailers
