:schedule:
  recalculate_videos_rank_job:
    every: 1h
    class: RecalculateVideosRankJob
  recalculate_tags_rank_job:
    every: 12h
    class: RecalculateTagsRankJob
  update_untagged_video_job:
    every: 1h
    class: UpdateUntaggedVideoJob
